apiVersion: batch/v1
kind: Job
metadata:
  name: test-pod
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 100
      containers:
        - name: browserless
          image: browserless/chrome:1-chrome-stable
        - name: auto-conv
          image: lyine/auto-conv:0.1.2
          env:
            - name: USERNAME
              value: ""
            - name: PASSWORD
              value: ""
            - name: BARKTOKEN
              value: ""
